### ISSUE TITLE
Parse exceptions

### ISSUE THREAD

**Issue by sahilahmadlone** [nuxeo/gatling-report#11]
This is giving me parse exceptions
Log FIle 
```
RUN	example.BasicSimulation		basicsimulation	1520337025119	TestJobName	2.0
USER	Scenario Name	1	START	1520337026234	1520337026234
REQUEST	Scenario Name	1		request_1	1520337026234	1520337028526	OK	 
REQUEST	Scenario Name	1		request_1 Redirect 1	1520337028527	1520337028570	OK	 
USER	Scenario Name	1	END	1520337026234	1520337028571
```
Command
`java -jar gatling-report-2.0-20171110.164656-1-capsule-fat.jar /var/folders/k8/_7_byqz53_s2h7v3k86wbsrc0000gp/T/61934b4e-ec7c-4f0d-8c83-6b5a83e3e3ce/basicsimulation-1520337025119/simulation.log`

Outpout 
```
Parsing /var/folders/k8/_7_byqz53_s2h7v3k86wbsrc0000gp/T/61934b4e-ec7c-4f0d-8c83-6b5a83e3e3ce/basicsimulation-1520337025119/simulation.log
Exception in thread "Thread-0" java.lang.NumberFormatException: For input string: "basicsimulation"
	at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
	at java.lang.Long.parseLong(Long.java:589)
	at java.lang.Long.parseLong(Long.java:631)
	at SimulationParser.parse(SimulationParser.java:62)
	at App.parseSimulationFile(App.java:58)
	at App.lambda$parseSimulationFiles$0(App.java:51)
	at java.util.ArrayList.forEach(ArrayList.java:1249)
	at App.parseSimulationFiles(App.java:51)
	at App.run(App.java:44)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by sahilahmadlone** [comment]
This report is from gatling

**Comment by bdelbosc** [comment]
yes, I think the problem is due to the format of the simulation.log. The format is different between Gatling 2.1, 2.2 and 2.3 while the version reported in the simulation.log is always "2.0". Your format looks like a 2.3 format and it is now supported with the latest gatling-report 3.0-SNAPSHOT.
