### ISSUE TITLE
Exception in thread "Thread-0" java.lang.NumberFormatException: For input string: "OK"

### ISSUE THREAD

**Issue by cdelorenzo** [nuxeo/gatling-report#15]
11:32:51,188 INFO  [App] Parsing simulation.log
Exception in thread "Thread-0" java.lang.NumberFormatException: For input string: "OK"
        at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
        at java.lang.Long.parseLong(Long.java:589)
        at java.lang.Long.parseLong(Long.java:631)
        at org.nuxeo.tools.gatling.report.SimulationParserV3.getRequestEnd(SimulationParserV3.java:64)
        at org.nuxeo.tools.gatling.report.SimulationParser.parse(SimulationParser.java:75)
        at org.nuxeo.tools.gatling.report.App.parseSimulationFile(App.java:66)
        at org.nuxeo.tools.gatling.report.App.lambda$parseSimulationFiles$0(App.java:59)
        at java.util.ArrayList.forEach(ArrayList.java:1257)
        at org.nuxeo.tools.gatling.report.App.parseSimulationFiles(App.java:59)
        at org.nuxeo.tools.gatling.report.App.run(App.java:53)
        at java.lang.Thread.run(Thread.java:748)

I have attached the simulation file generated.
[simulation.log](https://github.com/nuxeo/gatling-report/files/2853624/simulation.log)

versions tested with
  compile 'io.gatling:gatling-app:3.0.1.1'
  compile 'io.gatling.highcharts:gatling-charts-highcharts:3.0.1.1'

and
  compile 'io.gatling:gatling-app:3.0.3'
  compile 'io.gatling.highcharts:gatling-charts-highcharts:3.0.3'

**Comment by soernt** [comment]
Are there any updates for this issue??

**Comment by jaasal** [comment]
There is a pull request waiting which should fix this issue; https://github.com/nuxeo/gatling-report/pull/14

Hopefully this project is not completely abandoned yet.

**Comment by testgitdl** [comment]
Any feedback on this? I have a simulation file generated with 3.0.2 and I get the same error when parsing it with gatling-report in order to obtain a trend report. Thanks!

**Comment by bdelbosc** [comment]
#14 has been merged sorry for the delay, gatling-report also supports the latest Gatling 3.2.1 format.
