### ISSUE TITLE
Gatling 3.3.1 :(

### ISSUE THREAD

**Issue by igorrodygin** [nuxeo/gatling-report#18]
Failing with Gatling 3.3.1:

```
02:17:41,247 INFO  [App] Parsing /Users/igorrodygin/Documents/EXANTE/gitlab/gatling-load/results/loadscriptorderstypelimit-20200117220404777/simulation.log
Exception in thread "Thread-0" java.lang.IllegalArgumentException: Unknown Gatling simulation version: [RUN, load.LoadScriptOrdersTypeLimit, loadscriptorderstypelimit, 1579298644777,  , 3.3.1]
	at org.nuxeo.tools.gatling.report.ParserFactory.getVersionSpecificParser(ParserFactory.java:53)
	at org.nuxeo.tools.gatling.report.ParserFactory.getParser(ParserFactory.java:26)
	at org.nuxeo.tools.gatling.report.App.parseSimulationFile(App.java:65)
	at org.nuxeo.tools.gatling.report.App.lambda$parseSimulationFiles$0(App.java:59)
	at java.util.ArrayList.forEach(ArrayList.java:1257)
	at org.nuxeo.tools.gatling.report.App.parseSimulationFiles(App.java:59)
	at org.nuxeo.tools.gatling.report.App.run(App.java:53)
	at java.lang.Thread.run(Thread.java:748)
Igors-MacBook-Pro:17-01-2020 igorrodygin$ 
```

**Comment by igorrodygin** [comment]
need to rebuild, closed
