### ISSUE TITLE
.InvalidPathException

### ISSUE THREAD

**Issue by rajat007** [nuxeo/gatling-report#8]
While i am running the command 
java -jar path/to/gatling-report-VERSION-capsule-fat.jar path/to/simulation.log

I am getting the error so i had enabled the logs and in the below format  logs are 

CAPSULE: Starting capsule server.
CAPSULE: Binding capsule server at: 0.0.0.0:24886
CAPSULE: Using JVM: C:\Program Files\Java\jre1.8.0_121
CAPSULE: WARNING resolve [] was empty
CAPSULE: Cache directory: C:\Users\rsi142\AppData\Local\capsule
CAPSULE: Creating temp file/dir C:\Users\rsi142\AppData\Local\capsule\apps\gatling-report_1.0-SNAPSHOT\.lock
CAPSULE: Locking C:\Users\rsi142\AppData\Local\capsule\apps\gatling-report_1.0-SNAPSHOT\.lock
CAPSULE: Extracting C:\Users\rsi142\Desktop\gatling-charts-highcharts-bundle-2.2.2\results\9-1477563587925\gatling-report-1.0-20160706.134844-16-capsule-fat.jar to app cache directory C:\Users\rsi142\AppData\Local\capsule\apps\gatling-report_1.0-SNAPSHOT
CAPSULE: Unlocking C:\Users\rsi142\AppData\Local\capsule\apps\gatling-report_1.0-SNAPSHOT\.lock
CAPSULE: Cleanup
CAPSULE EXCEPTION: Illegal char <:> at index 52: C:\Program Files\Common Files\Intel\WirelessCommon\C:\Program Files\Java\jdk1.7.0_76\bin
java.nio.file.InvalidPathException: Illegal char <:> at index 52: C:\Program Files\Common Files\Intel\WirelessCommon\C:\Program Files\Java\jdk1.7.0_76\bin
        at sun.nio.fs.WindowsPathParser.normalize(Unknown Source)
        at sun.nio.fs.WindowsPathParser.parse(Unknown Source)
        at sun.nio.fs.WindowsPathParser.parse(Unknown Source)
        at sun.nio.fs.WindowsPath.parse(Unknown Source)
        at sun.nio.fs.WindowsFileSystem.getPath(Unknown Source)
        at Capsule.path(Capsule.java:3656)
        at Capsule.toPath(Capsule.java:3668)
        at Capsule.getPlatformNativeLibraryPath0(Capsule.java:2431)
        at Capsule.getPlatformNativeLibraryPath(Capsule.java:2424)
        at Capsule.buildNativeLibraryPath(Capsule.java:2406)
        at Capsule.buildSystemProperties(Capsule.java:2368)
        at Capsule.buildSystemProperties(Capsule.java:2349)
        at Capsule.buildJavaProcess(Capsule.java:2217)
        at Capsule.buildProcess0(Capsule.java:1519)
        at Capsule.buildProcess(Capsule.java:1510)
        at Capsule.prelaunch0(Capsule.java:1483)
        at Capsule.prelaunch(Capsule.java:1476)
        at Capsule.prepareForLaunch(Capsule.java:1329)
        at Capsule.launch(Capsule.java:1258)
        at Capsule.main0(Capsule.java:394)
        at Capsule.main(Capsule.java:374)
USAGE: java <options> -jar gatling-report-1.0-20160706.134844-16-capsule-fat.jar

**Comment by bdelbosc** [comment]
Hi, it sounds like a windows capsule problem, try again with latest release and reopen if needed.
